remote_theme: "mmistakes/so-simple-theme@3.2.0"
skin: "/assets/css/skins/default.css"
locale: en-US
title: "DavidETheresa"
description: "We're happy that you're going to spend this day with us."
url: "https://davidetheresa.github.io"
logo: "/assets/images/logo.jpg"

google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"

# Build settings
markdown: kramdown

# Pagination
paginate: 10
paginate_path: /page:num/


plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

# Collections
collections:
  location:
    output: true
    permalink: /:collection/:path/

  accomodation:
    output: true
    permalink: /:collection/:path/

  travel:
    output: true
    permalink: /:collection/:path/


# Front Matter Defaults
defaults:
  # Info page defaults
  - scope:
      path: "_accomodation"
      type: accomodation
    values:
      layout: post

  - scope:
      path: "_travel"
      type: travel
    values:
      layout: post

  - scope:
      path: "_location"
      type: location
    values:
        layout: post

